apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-nginx
  template:
    metadata:
      labels:
        app: argo-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        containers:
      - name: nginx
        image: nagarajanroshen/argo-nginx-demo:latest
        - name: Build Image
     run: docker build -t nagarajanp/argo-nginx-demo:latest ./app

  - name: Push Image
     run: docker push nagarajanp/argo-nginx-demo:latest
